# Generated by Django 4.1.4 on 2023-02-06 04:50

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=200)),
                ('imagefile', models.ImageField(blank=True, null=True, upload_to=pathlib.PureWindowsPath('C:/Users/김진산/Documents/workspace/django/myphoto/media'))),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
