# Generated by Django 4.1.4 on 2023-02-03 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='autho',
            new_name='author',
        ),
    ]
