# Generated by Django 4.1.4 on 2023-02-03 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_rename_autho_photo_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='decription',
            new_name='description',
        ),
    ]
