# Generated by Django 4.1.4 on 2023-02-07 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='imagefile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
