# Generated by Django 4.1.4 on 2023-02-06 04:57

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='imagefile',
            field=models.ImageField(blank=True, null=True, upload_to=pathlib.PureWindowsPath('C:/Users/김진산/Documents/workspace/django/photo02/media')),
        ),
    ]
